version: '3'
services:

  postgres:
    # For more details on configuring the Postgres Docker image, see:
    #   https://hub.docker.com/_/postgres/
    image: tparker/gwas
    restart: always
    ports:
      - '5434:5432'
    network_mode: bridge
    container_name: pgtinyint

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pgpass'
      POSTGRES_DB: 'postgres'

    # Copy files from dbinit into the image so that they will be run on boot
    # volumes:
      # - ./init.sh:/docker-entrypoint-initdb.d
